apiVersion: v1
kind: Service
metadata:
  name: demo-prod
  labels:
    app: demo-prod
spec:
  ports:
  - nodePort: 32000
    protocol: TCP
    port: 8080
  selector:
    app: demo-prod
  type: NodePort
